myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('pcportal/', include('pcportal.urls')),
                  path('', RedirectView.as_view(url='pcportal/', permanent=False)),
                  # path('tinymce/', include('tinymce.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pcportal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # main
    path('', views.index, name='index_n'),

    # user profile
    path('register/', views.register_user, name='register'),
    path('profile/', views.get_user_profile, name='user-profile'),

    # sellers
    path('sellers/', views.SellerListView.as_view(), name='sellers-all'),
    path('sellers/<int:pk>', views.SellerDetailView.as_view(), name='seller-one'),

    # user listings
    path('mylistings/', views.get_user_listings, name='my-listings'),
    # seller listings
    path('sellers/<int:seller_id>/pcbuildlistings/', views.get_seller_listings, name='seller-listings'),

    # all listings
    path('partlistings/', views.get_part_listings, name='part-listings'),
    path('pcbuildlistings/', views.PcBuildListingListView.as_view(), name='pcbuild-listings'),

    # all parts list
    path('parts/', views.get_all_parts, name='part-list'),

    # individual listings
    path('pcbuildlistings/<int:pk>', views.PcBuildListingDetailView.as_view(), name='pcbuild-listing-one'),
    path('partlistings/cpu/<int:pk>', views.CpuListingDetailView.as_view(), name='cpu-listing-one'),
    path('partlistings/gpu/<int:pk>', views.GpuListingDetailView.as_view(), name='gpu-listing-one'),
    path('partlistings/psu/<int:pk>', views.PsuListingDetailView.as_view(), name='psu-listing-one'),
    path('partlistings/ram/<int:pk>', views.RamListingDetailView.as_view(), name='ram-listing-one'),
    path('partlistings/storage/<int:pk>',
         views.StorageListingDetailView.as_view(), name='storage-listing-one'),
    path('partlistings/casepc/<int:pk>',
         views.CasePCListingDetailView.as_view(), name='casepc-listing-one'),
    path('partlistings/motherboard/<int:pk>',
         views.MotherboardListingDetailView.as_view(), name='motherboard-listing-one'),
    path('partlistings/cpucooler/<int:pk>',
         views.CpuCoolerListingDetailView.as_view(), name='cpucooler-listing-one'),

    # search
    path('sellers/search/', views.search_seller, name='search-seller'),
    path('partlistings/search/', views.search_part_listings_by_price, name='search-partlistings'),
    path('pcbuildlistings/search/', views.search_pcbuildlisting, name='search-pcbuildlisting'),

    # delete
    path('mylistings/cpu/delete/<int:pk>', views.CpuListingByUserDeleteView.as_view(),
         name='user-delete-cpulisting'),
    path('mylistings/gpu/delete/<int:pk>', views.GpuListingByUserDeleteView.as_view(),
         name='user-delete-gpulisting'),
    path('mylistings/psu/delete/<int:pk>', views.PsuListingByUserDeleteView.as_view(),
         name='user-delete-psulisting'),
    path('mylistings/ram/delete/<int:pk>', views.RamListingByUserDeleteView.as_view(),
         name='user-delete-ramlisting'),
    path('mylistings/storage/delete/<int:pk>', views.StorageListingByUserDeleteView.as_view(),
         name='user-delete-storagelisting'),
    path('mylistings/casepc/delete/<int:pk>', views.CasePCListingByUserDeleteView.as_view(),
         name='user-delete-casepclisting'),
    path('mylistings/motherboard/delete/<int:pk>', views.MotherboardListingByUserDeleteView.as_view(),
         name='user-delete-motherboardlisting'),
    path('mylistings/cpucooler/delete/<int:pk>', views.CpuCoolerListingByUserDeleteView.as_view(),
         name='user-delete-cpucoolerlisting'),
    path('mylistings/pcbuildlisting/delete/<int:pk>', views.PcBuildListingByUserDeleteView.as_view(),
         name='user-delete-pcbuildlisting'),

    # update listings
    path('mylistings/cpu/update/<int:pk>', views.CpuListingByUserUpdateView.as_view(),
         name='user-update-cpulisting'),
    path('mylistings/gpu/update/<int:pk>', views.GpuListingByUserUpdateView.as_view(),
         name='user-update-gpulisting'),
    path('mylistings/psu/update/<int:pk>', views.PsuListingByUserUpdateView.as_view(),
         name='user-update-psulisting'),
    path('mylistings/ram/update/<int:pk>', views.RamListingByUserUpdateView.as_view(),
         name='user-update-ramlisting'),
    path('mylistings/storage/update/<int:pk>', views.StorageListingByUserUpdateView.as_view(),
         name='user-update-storagelisting'),
    path('mylistings/casepc/update/<int:pk>', views.CasePCListingByUserUpdateView.as_view(),
         name='user-update-casepclisting'),
    path('mylistings/motherboard/update/<int:pk>', views.MotherboardListingByUserUpdateView.as_view(),
         name='user-update-motherboardlisting'),
    path('mylistings/cpucooler/update/<int:pk>', views.CpuCoolerListingByUserUpdateView.as_view(),
         name='user-update-cpucoolerlisting'),
    path('mylistings/pcbuildlisting/<int:pk>', views.PcBuildListingByUserUpdateView.as_view(),
         name='user-update-pcbuildlisting'),

    # create listings
    path('createlistings/cpulisting/', views.CpuListingByUserCreateView.as_view(),
         name='create-cpulisting'),
    path('createlistings/gpulisting/', views.GpuListingByUserCreateView.as_view(),
         name='create-gpulisting'),
    path('createlistings/psulisting/', views.PsuListingByUserCreateView.as_view(),
         name='create-psulisting'),
    path('createlistings/ramlisting/', views.RamListingByUserCreateView.as_view(),
         name='create-ramlisting'),
    path('createlistings/storagelisting/', views.StorageListingByUserCreateView.as_view(),
         name='create-storagelisting'),
    path('createlistings/casepclisting/', views.CasePCListingByUserCreateView.as_view(),
         name='create-casepclisting'),
    path('createlistings/motherboardlisting/', views.MotherboardListingByUserCreateView.as_view(),
         name='create-motherboardlisting'),
    path('createlistings/cpucoolerlisting/', views.CpuCoolerListingByUserCreateView.as_view(),
         name='create-cpucoolerlisting'),
    path('createlistings/pcbuildlisting/', views.PcBuildListingByUserCreateView.as_view(),
         name='create-pcbuildlisting'),

    # liking PC build listings
    path('likepcbuildlistings/<int:pcbuildlisting_id>', views.like_pcbuildlistings,
         name='like-pcbuildlistings'),
    path('likepcbuildlisting/<int:pcbuildlisting_id>', views.like_pcbuildlisting,
         name='like-pcbuildlisting'),
]

pcportal/models/build_with_listing.py
from datetime import date
from .seller_model import *
from .part_models import *
from django.contrib.auth.models import User


class PcBuild(models.Model):
    """
    PcBuild model stores information about Pc builds.
    title - the name of Pc,
    cpu, cpu cooler, gpu, psu, motherboard, pc case,
    all these parts are accessed through a foreign key to each.
    ram and storage parts through related_name, then they are gathered
    if they are multiple and returned as f strings.
    """
    title = models.CharField("PC name", max_length=50, blank=True, null=True)
    cpu = models.ForeignKey(Cpu, on_delete=models.SET_NULL, blank=True, null=True)
    cpucooler = models.ForeignKey(CpuCooler, on_delete=models.SET_NULL, blank=True, null=True)
    gpu = models.ForeignKey(Gpu, on_delete=models.SET_NULL, blank=True, null=True)
    psu = models.ForeignKey(Psu, on_delete=models.SET_NULL, blank=True, null=True)
    motherboard = models.ForeignKey(Motherboard, on_delete=models.SET_NULL, blank=True, null=True)
    pc_case = models.ForeignKey(CasePC, on_delete=models.SET_NULL, blank=True, null=True)

    def title_disp(self):
        """
        This function displays pc build's title
        if there isn't one, returns Untitled.
        """
        if self.title:
            return f"{self.title}"
        else:
            return "Untitled"

    title_disp.short_description = "PC name"

    def cpu_disp(self):
        """
        This function displays cpu brand and model.
        """
        if self.cpu:
            return f"{self.cpu.brand} {self.cpu.cpu_model}"
        else:
            return "No Cpu"

    cpu_disp.short_description = "CPU"

    def cooler_disp(self):
        """
        This function displays a cpu cooler.
        """
        if self.cpucooler:
            return f"{self.cpucooler.cooler_name}"
        else:
            return "No CPU cooler"

    cooler_disp.short_description = "CPU COOLER"

    def gpu_disp(self):
        """
        This function displays a gpu model.
        """
        if self.gpu:
            return f"{self.gpu.gpu_model}"
        else:
            return "No GPU"

    gpu_disp.short_description = "GPU"

    def psu_disp(self):
        """
        This function displays a PSU.
        """
        if self.psu:
            return f"{self.psu.psu_name}"
        else:
            return "No PSU"

    psu_disp.short_description = "PSU"

    def motherboard_disp(self):
        """
        This function displays a Motherboard.
        """
        if self.motherboard:
            return f"{self.motherboard.motherboard_name}"
        else:
            return "No motherboard"

    motherboard_disp.short_description = "MOTHERBOARD"

    def casepc_disp(self):
        """
        This function displays a PC case.
        """
        if self.pc_case:
            return f"{self.pc_case.case_name}"
        else:
            return "No pc case"

    casepc_disp.short_description = "PC CASE"

    def ram_disp(self):
        """
        This functions uses related_name (ram) and
        then joins ram quantity and capacity into f strings
        and returns them.
        """
        # noinspection PyUnresolvedReferences
        if self.ram.exists():
            ram_detes = []
            # noinspection PyUnresolvedReferences
            for ram_build in self.ram.all():
                ram_detes.append(f"{ram_build.quantity}x{ram_build.ram.capacity}GB")
            rams = ', '.join(ram_detes)
            return f"{rams} RAM"
        else:
            return "No RAMs"

    ram_disp.short_description = "RAM"

    def storage_disp(self):
        """
        This functions uses related_name (storage) and
        then joins storage quantity, capacity, type
        into f strings and returns them.
        """
        # noinspection PyUnresolvedReferences
        if self.storage.exists():
            storages_detes = []
            # noinspection PyUnresolvedReferences
            for storage_build in self.storage.all():
                storages_detes.append(f"{storage_build.quantity}x{storage_build.storage.capacity}GB "
                                      f"{storage_build.storage.storage_type}")
            storages = ', '.join(storages_detes)
            return f"{storages}"
        else:
            return "No storage"

    storage_disp.short_description = "Storage"

    def __str__(self):
        return f"{self.cpu_disp()} {self.gpu_disp()}, {self.ram_disp()}, {self.storage_disp()}"


# RAM quantity and Storage quantity for PC BUILD

class RamBuild(models.Model):
    """
    This class uses a foreign key to link RAM
    to a specific pc build while also setting quantity of
    RAM sticks
    """
    quantity = models.IntegerField("RAM quantity",
                                   help_text="Quantity of RAMs")
    ram = models.ForeignKey(Ram, on_delete=models.CASCADE)
    pcbuild = models.ForeignKey(PcBuild, on_delete=models.CASCADE, related_name="ram")

    def ram_title(self):
        """
        returns ram name and type.
        """
        return f"{self.ram.ram_name} {self.ram.ram_type}"

    def ram_capacity(self):
        """
        returns ram capacity in GB,
        calls ram_display() through ram foreign key.
        """
        return f"{self.ram.ram_display()}"

    def ram_speed(self):
        """
        returns ram speed in GHz,
        calls speed_display() through ram foreign key.
        """
        return f"{self.ram.speed_display()}"

    def pc_build_name(self):
        """
        returns pc build's title
        calls title_disp() through pcbuild foreign key.
        """
        return f"{self.pcbuild.title_disp()}"

    def __str__(self):
        return (f"{self.ram.ram_name}, {self.quantity}x{self.ram.capacity}, "
                f"{self.ram.ram_type}, {self.ram.ram_speed}, {self.pcbuild.title}")

    class Meta:
        verbose_name = "RAM stick for a build"
        verbose_name_plural = "RAM sticks for a build"


class StorageBuild(models.Model):
    """
    This class uses a foreign key to link storage devices
    to a specific pc build while also setting quantity of
    storage devices
    """
    quantity = models.IntegerField("Storage quantity",
                                   help_text="Quantity of Storage devices")
    storage = models.ForeignKey(Storage, on_delete=models.CASCADE)
    pcbuild = models.ForeignKey(PcBuild, on_delete=models.CASCADE, related_name="storage")

    def storage_title(self):
        """
        returns storage's title.
        """
        return f"{self.storage.storage_name}"

    def storage_capacity(self):
        """
        returns storage's type and capacity in GB.
        """
        return f"{self.storage.storage_type} {self.storage.capacity_display()}"

    def storage_write_speed(self):
        """
        returns storage's write speed.
        """
        return f"{self.storage.write_display()}"

    def storage_read_speed(self):
        """
        returns storage's read speed.
        """
        return f"{self.storage.read_display()}"

    def __str__(self):
        return (f"{self.storage.storage_name}, {self.storage.storage_type}, "
                f"{self.quantity}x{self.storage.capacity}GB")

    class Meta:
        verbose_name = "Storage device for a build"
        verbose_name_plural = "Storage devices for a build"


# PC build listing model

class PcBuildListing(models.Model):
    """
    This class links pc build to a seller,
    allowing to set price for a pc build,
    condition and description.
    """
    price = models.FloatField("Price")
    date_created = models.DateField("Date listed", auto_now_add=True)

    expiration_date = models.DateField("Expiration date", default="2025-03-20")

    PC_CONDITION = (
        ("full", "Full build"),
        ("incomplete", "Incomplete"),
        ("pre-owned", "Pre-owned"),
    )
    condition = models.CharField("PC condition", choices=PC_CONDITION,
                                 help_text="Is is a full build, incomplete or used",
                                 max_length=30)

    description = models.TextField("Description",
                                   max_length=500, blank=True, null=True,
                                   help_text="PC build description, information")
    pc_build = models.ForeignKey(PcBuild, on_delete=models.CASCADE, related_name="pcbuildlisting")
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, related_name="pcbuildlisting")

    listing_seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def exp_status(self):
        """
        This property function checks if
        expiration date is past date or not,
        then returns Expired or Active
        """
        if self.expiration_date < date.today():
            return "Expired"
        return "Active"

    @property
    def count_likes(self):
        # noinspection PyUnresolvedReferences
        return self.likes.count()

    def pc_name(self):
        """
        This function returns PC build's brand and model.
        """
        return f"{self.pc_build.title}"

    def main_specs(self):
        """
        This function returns PC build's main specifications.
        """
        return f"{self.pc_build.gpu_disp()}, {self.pc_build.cpu_disp()}, {self.pc_build.ram_disp()}"

    def display_seller(self):
        return f"{self.seller.f_name} {self.seller.l_name}"

    display_seller.short_description = "SELLER"

    def __str__(self):
        return (f"{self.pc_name()} {self.date_created}. price - {self.price}, "
                f"condition - {self.condition}, seller - {self.seller}")


class UserLikes(models.Model):
    """
    This model stores 'user likes' in a
    table, user foreign key and pc build listing,
    each can have one like from one user.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="likes")

pcportal/models/profile_model.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    """
    This model stores information about
    a user's profile, let's users upload or
    change their profile picture.
    """
    picture = models.ImageField(upload_to='profile_pics', default='default_user.png')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.picture.path)
        thumb_size = (200, 200)
        img.thumbnail(thumb_size)
        img.save(self.picture.path)

pcportal/templates/one_listing_templates/listing_casepc.html
{% extends 'base.html' %}

{% block content %}
{% if casepc_listing %}
<h1>{{ casepc_listing.casepc.casepc_name }}</h1>
<p>Listing details are bellow:</p>
<ul class="list-group">

    <li class="list-group-item">
        <p>Date listed <em><b>{{ casepc_listing.date_created }}</b></em>,
            Expiration date - <em><b>{{ casepc_listing.expiration_date }}</b></em>,
            <b style="display: inline;"
            class="{% if casepc_listing.exp_status == 'Active' %} text-success
            {% else %} text-danger
            {% endif %}"><em> {{ casepc_listing.exp_status }}</em></b>
            </p>
            <p>number of PC cases - {{ casepc_listing.quantity }}</p>
                <p>price per one - {{ casepc_listing.price }}</p>
        <p>{{ casepc_listing.casepc.case_name }}, {{ casepc_listing.casepc.get_case_size_display }}</p>
        <p>Seller: {{ casepc_listing.display_seller }}
        <a href="{% url 'seller-one' casepc_listing.seller.id %}"><b>visit seller</b>
        </a>
        </p>
    </li>

</ul>
{% else %}
No PC case listing found
{% endif %}
{% endblock %}
{% block title %}<title>{{ casepc_listing.casepc.casepc_name }}</title>{% endblock %}

pcportal/templates/one_listing_templates/listing_cpu.html
{% extends 'base.html' %}

{% block content %}

{% if cpu_listing %}
<h1>{{ cpu_listing.cpu.cpu_model }}</h1>
<p>Listing details are bellow:</p>
<ul class="list-group">

        <li class="list-group-item">
        <p>Date listed <em><b>{{ cpu_listing.date_created }}</b></em>,
            Expiration date - <em><b>{{ cpu_listing.expiration_date }}</b></em>,
            <b style="display: inline;"
            class="{% if cpu_listing.exp_status == 'Active' %} text-success
            {% else %} text-danger
            {% endif %}"><em> {{ cpu_listing.exp_status }}</em></b>
            </p>
                <p>number of CPUs - {{ cpu_listing.quantity }}</p>
                    <p>price per one - {{ cpu_listing.price }}</p>
            <p>{{ cpu_listing.cpu.brand }} {{ cpu_listing.cpu.cpu_model }} {{ cpu_listing.cpu.base_clock_speed }}GHz
                {{ cpu_listing.cpu.socket_type }}, {{ cpu_listing.cpu.cores }} cores</p>
            <p>Seller: {{ cpu_listing.display_seller }}
            <a href="{% url 'seller-one' cpu_listing.seller.id %}"><b>visit seller</b>
            </a>
            </p>
        </li>

</ul>
{% else %}
No CPU listing found
{% endif %}
{% endblock %}
{% block title %}<title>{{ cpu_listing.cpu.cpu_model }}</title>{% endblock %}

pcportal/templates/one_listing_templates/listing_pcbuild.html
{% extends 'base.html' %}

{% block content %}

{% if pcbuildlisting %}
<h1>{{ pcbuildlisting.pc_name }}</h1>
<p>here are {{ pcbuildlisting.pc_name }} details</p>
<ul class="list-group">

    <li class="list-group-item">
        <p>{{ pcbuildlisting.pc_name }}</p>
            <p>Date listed <em><b>{{ pcbuildlisting.date_created }}</b></em>,
            Expiration date - <em><b>{{ pcbuildlisting.expiration_date }}</b></em>,
            <b style="display: inline;"
            class="{% if pcbuildlisting.exp_status == 'Active' %} text-success
            {% else %} text-danger
            {% endif %}"><em> {{ pcbuildlisting.exp_status }}</em></b>
            </p>
    <p>
        price - {{ pcbuildlisting.price }}</p>
    <p>
        conditon -
        <b style="display: inline;"
            class="{% if pcbuildlisting.condition == 'full' %} text-success
        {% elif pcbuildlisting.condition == 'incomplete' %} text-warning
        {% else %} text-info
        {% endif %}"><em>{{ pcbuildlisting.get_condition_display }}</em></b>
    </p>
        <p>
            {{ pcbuildlisting.pc_build.cpu_disp }}, {{ pcbuildlisting.pc_build.gpu_disp }},
            {{ pcbuildlisting.pc_build.motherboard_disp }},
            {{ pcbuildlisting.pc_build.ram_disp }}  {{ pcbuildlisting.pc_build.storage_disp }}
        </p>
        <p>{{ pcbuildlisting.description }}</p><p>{{ pcbuildlisting.display_seller }}
            <a href="{% url 'seller-one' pcbuildlisting.seller.id %}"><b>visit seller</b></a>
        </p>
        <p><b>User likes: {{ pcbuildlisting.count_likes }}</b></p>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'like-pcbuildlisting' pcbuildlisting.id %}">
                {% csrf_token %}
                {% if pcbuildlisting.user_liked %}
                    <button type="submit" class="btn btn-outline-danger"><b>Unlike</b></button>
                {% else %}
                    <button type="submit" class="btn btn-outline-success"><b>Like</b></button>
                {% endif %}
            </form>
        {% endif %}

        <table>
            <tr>
                <th colspan="2">CPU</th>
            </tr>
            <tr> <td>Brand</td> <td>{{ pcbuildlisting.pc_build.cpu.brand }}</td> </tr>
            <tr> <td>Model</td> <td>{{ pcbuildlisting.pc_build.cpu.cpu_model }}</td> </tr>
            <tr> <td>Number of cores</td> <td>{{ pcbuildlisting.pc_build.cpu.cores}}</td> </tr>
            <tr> <td>Base clock speed</td> <td>{{ pcbuildlisting.pc_build.cpu.speed_display }}</td> </tr>
            <tr> <td>Socket type</td> <td>{{ pcbuildlisting.pc_build.cpu.socket_type }}</td> </tr>

            <tr>
                <th colspan="2">GPU</th>
            </tr>
            <tr> <td>Brand</td> <td>{{ pcbuildlisting.pc_build.gpu.brand }}</td> </tr>
            <tr> <td>Model</td> <td>{{ pcbuildlisting.pc_build.gpu.gpu_model }}</td> </tr>
            <tr> <td>VRAM</td> <td>{{ pcbuildlisting.pc_build.gpu.vram_display }}</td> </tr>
            <tr> <td>Clock speed</td> <td>{{ pcbuildlisting.pc_build.gpu.speed_display }}</td> </tr>

            <tr>
                <th colspan="2">Motherboard</th>
            </tr>
            <tr> <td>Name</td> <td>{{ pcbuildlisting.pc_build.motherboard.motherboard_name }}</td> </tr>
            <tr> <td>Chipset</td> <td>{{ pcbuildlisting.pc_build.motherboard.chipset }}</td> </tr>
            <tr> <td>Socket type</td> <td>{{ pcbuildlisting.pc_build.motherboard.socket_type}}</td> </tr>
            <tr> <td>Ram type</td> <td>{{ pcbuildlisting.pc_build.motherboard.get_ram_type_display }}</td> </tr>
            <tr> <td>Board size</td> <td>{{ pcbuildlisting.pc_build.motherboard.get_board_size_display }}</td> </tr>
            <tr> <td>Maximum ram capacity</td> <td>{{ pcbuildlisting.pc_build.motherboard.ram_display }}</td> </tr>

            <tr>
                <th colspan="2">PSU</th>
            </tr>
            <tr> <td>PSU name</td> <td>{{ pcbuildlisting.pc_build.psu.psu_name }}</td> </tr>
            <tr> <td>Wattage</td> <td>{{ pcbuildlisting.pc_build.psu.wattage }}W</td> </tr>
            <tr> <td>Efficiency rating</td> <td>{{ pcbuildlisting.pc_build.psu.get_efficiency_display }}</td> </tr>

            <tr>
                <th colspan="2">CPU cooler</th>
            </tr>
            <tr> <td>Cooler name</td> <td>{{ pcbuildlisting.pc_build.cpucooler.cooler_name }}</td> </tr>
            <tr> <td>Cooler type</td> <td>{{ pcbuildlisting.pc_build.cpucooler.get_cooler_type_display }}</td> </tr>
            <tr> <td>Maximum cooler power</td> <td>{{ pcbuildlisting.pc_build.cpucooler.max_power }}W</td> </tr>
            <tr> <td>Fan size</td> <td>{{ pcbuildlisting.pc_build.cpucooler.fan_size }}mm</td> </tr>

            {% if pcbuildlisting.pc_build.ram.all %}
                    <tr>
                        <th colspan="2">RAM</th>
                    </tr>
                {% for rams in pcbuildlisting.pc_build.ram.all %}
                    <tr> <td colspan="2"><b><em>{{ rams.ram.ram_name }}</em></b></td></tr>
                    <tr> <td>Capacity</td> <td>{{ rams.quantity }}x{{ rams.ram_capacity }}</td> </tr>
                    <tr> <td>Type</td> <td>{{ rams.ram.get_ram_type_display }}</td> </tr>
                    <tr> <td>Speed</td> <td>{{ rams.ram.speed_display }}</td> </tr>

                {% endfor %}
            {% else %}
                    <tr><th colspan="2">RAM</th></tr>
                <tr> <td colspan="2">No RAM modules</td> </tr>
            {% endif %}

            {% if pcbuildlisting.pc_build.storage.all %}
                    <tr>
                        <th colspan="2">Storage</th>
                    </tr>
                {% for storages in pcbuildlisting.pc_build.storage.all %}
                    <tr> <td colspan="2"><b><em>{{ storages.storage.storage_name }}</em></b></td> </tr>
                    <tr> <td>Capacity</td> <td>{{ storages.quantity }}x{{ storages.storage.capacity_display }}</td> </tr>
                    <tr> <td>Type</td> <td>{{ storages.storage.get_storage_type_display }}</td> </tr>
                    <tr> <td>Write speed</td> <td>{{ storages.storage.write_display }}</td> </tr>
                    <tr> <td>Read speed</td> <td>{{ storages.storage.read_display }}</td> </tr>

                {% endfor %}
            {% else %}
                    <tr><th colspan="2">Storage</th></tr>
                <tr> <td colspan="2">No storage devices</td> </tr>
            {% endif %}

            <tr>
                <th colspan="2">PC case</th>
            </tr>
            <tr> <td>Brand</td> <td>{{ pcbuildlisting.pc_build.pc_case.case_name }}</td> </tr>
            <tr> <td>Clock speed</td> <td>{{ pcbuildlisting.pc_build.pc_case.get_case_size_display }}</td> </tr>

        </table>

        <p>
            <a href="{% url 'seller-one' pcbuildlisting.seller.id %}"><b>visit seller</b></a>
        </p>
    </li>


</ul>
{% else %}
No PC build listing found
{% endif %}

{% endblock %}
{% block title %}<title>{{ pcbuildlisting.pc_name }}</title>{% endblock %}